# Generated by Django 4.0.1 on 2022-01-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=30)),
                ('team_number', models.IntegerField()),
                ('emp_rank', models.CharField(max_length=30)),
                ('emp_responsibilities', models.CharField(max_length=50)),
                ('monthly_salary', models.IntegerField()),
                ('entry_date', models.DateField(null=True)),
            ],
        ),
    ]
