# Generated by Django 4.0.1 on 2022-01-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, upload_to='emp/images/6a4e76af-446f-4bb0-a5de-38e092c1acbc/'),
        ),
    ]
