# Generated by Django 4.0.1 on 2022-01-23 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emp', '0002_employee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='empp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, upload_to='emp/images/93c7a80a-f845-4afd-8863-6cab106db442/'),
        ),
    ]
