# Generated by Django 4.0.1 on 2022-01-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0004_alter_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, upload_to='emp/images/b4881498-24df-4c18-a67d-d955433ed668/'),
        ),
    ]
