# Generated by Django 4.0.1 on 2022-01-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=30)),
                ('team_position', models.CharField(max_length=100)),
                ('team_explanation', models.TextField()),
            ],
        ),
    ]
